#!/usr/bin/env python3
"""Generate small, self-hosted SVG cards for the profile README."""

import html
import json
import os
import pathlib
import urllib.parse
import urllib.request
from datetime import datetime, timezone

USER = "hncjxywyh"
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "output"
ACCENT = "#7c5cff"
LANG_COLORS = {
    "Python": "#3572A5", "Java": "#b07219", "JavaScript": "#f1e05a",
    "TypeScript": "#2b7489", "HTML": "#e34c26", "CSS": "#563d7c",
    "Shell": "#89e051", "Jupyter Notebook": "#DA5B0B",
}


def api(path):
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "profile-stats"}
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request("https://api.github.com" + path, headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def esc(value):
    return html.escape(str(value or ""), quote=True)


def svg(width, height, body):
    style = """
    <style>
      text { font-family: Segoe UI, PingFang SC, Microsoft YaHei, sans-serif; }
      .bg { fill: #ffffff; stroke: #d0d7de; }
      .card { fill: #f6f8fa; stroke: #d0d7de; }
      .title { font-size: 15px; font-weight: 600; fill: #1f2328; }
      .label { font-size: 13px; fill: #57606a; }
      .value { font-size: 13px; font-weight: 600; fill: #1f2328; }
      .muted { font-size: 11px; fill: #8c959f; }
      .repo { font-size: 14px; font-weight: 600; fill: #0969da; }
      @media (prefers-color-scheme: dark) {
        .bg { fill: #0d1117; stroke: #30363d; }
        .card { fill: #161b22; stroke: #30363d; }
        .title, .value { fill: #e6edf3; }
        .label { fill: #8b949e; }
        .muted { fill: #6e7681; }
        .repo { fill: #58a6ff; }
      }
    </style>
    """
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">{style}{body}</svg>\n'


def clip(text, limit):
    text = str(text or "")
    return text if len(text) <= limit else text[: limit - 1] + "…"


def build_stats(user, repos):
    stars = sum(repo.get("stargazers_count", 0) for repo in repos)
    forks = sum(repo.get("forks_count", 0) for repo in repos)
    rows = [
        ("Public repos", user.get("public_repos", 0), ACCENT),
        ("Total stars", stars, "#e3b341"),
        ("Total forks", forks, "#3fb950"),
        ("Followers", user.get("followers", 0), "#a371f7"),
        ("Following", user.get("following", 0), "#58a6ff"),
        ("Public gists", user.get("public_gists", 0), "#f778ba"),
    ]
    body = ['<rect class="bg" x="0.5" y="0.5" width="479" height="179" rx="10"/>', '<text class="title" x="24" y="38">GitHub activity</text>', '<line x1="24" y1="52" x2="456" y2="52" stroke="#d0d7de" stroke-opacity=".6"/>']
    for index, (label, value, color) in enumerate(rows):
        column, row = index % 2, index // 2
        x, y = 24 + column * 224, 84 + row * 34
        body += [f'<circle cx="{x + 5}" cy="{y - 4}" r="5" fill="{color}"/>', f'<text class="label" x="{x + 18}" y="{y}">{esc(label)}:</text>', f'<text class="value" x="{x + 196}" y="{y}" text-anchor="end">{value}</text>']
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    body.append(f'<text class="muted" x="24" y="168">updated {today} · generated by GitHub Actions</text>')
    return svg(480, 180, "".join(body))


def build_languages(language_bytes):
    total = sum(language_bytes.values()) or 1
    items = sorted(language_bytes.items(), key=lambda item: item[1], reverse=True)[:6]
    height = 62 + len(items) * 30
    body = [f'<rect class="bg" x="0.5" y="0.5" width="479" height="{height - 1}" rx="10"/>', '<text class="title" x="24" y="38">Top languages</text>', '<line x1="24" y1="52" x2="456" y2="52" stroke="#d0d7de" stroke-opacity=".6"/>']
    for index, (name, amount) in enumerate(items):
        percent = amount / total * 100
        y = 76 + index * 30
        color = LANG_COLORS.get(name, "#8b949e")
        body += [f'<text class="label" x="24" y="{y + 4}">{esc(clip(name, 18))}</text>', f'<rect class="card" x="150" y="{y - 6}" width="250" height="10" rx="5"/>', f'<rect x="150" y="{y - 6}" width="{max(4, int(250 * percent / 100))}" height="10" rx="5" fill="{color}"/>', f'<text class="muted" x="456" y="{y + 4}" text-anchor="end">{percent:.1f}%</text>']
    return svg(480, height, "".join(body))


def build_repos(repos):
    picked = sorted(repos, key=lambda repo: (repo.get("stargazers_count", 0), repo.get("pushed_at", "")), reverse=True)[:4]
    width, card_width, card_height, gap, pad = 518, 238, 106, 14, 14
    height = card_height * 2 + gap + pad * 2
    body = [f'<rect class="bg" x="0.5" y="0.5" width="{width - 1}" height="{height - 1}" rx="10"/>']
    for index, repo in enumerate(picked):
        column, row = index % 2, index // 2
        x, y = pad + column * (card_width + gap), pad + row * (card_height + gap)
        name = clip(repo.get("name"), 24)
        description = clip(repo.get("description") or "Project repository", 33)
        body += [f'<rect class="card" x="{x}" y="{y}" width="{card_width}" height="{card_height}" rx="8"/>', f'<text class="repo" x="{x + 14}" y="{y + 26}">{esc(name)}</text>', f'<text class="label" x="{x + 14}" y="{y + 48}">{esc(description)}</text>', f'<text class="muted" x="{x + 14}" y="{y + 82}">★ {repo.get("stargazers_count", 0)}   ⑂ {repo.get("forks_count", 0)}</text>']
    return svg(width, height, "".join(body))


def main():
    OUT.mkdir(exist_ok=True)
    user = api(f"/users/{urllib.parse.quote(USER)}")
    repos = [repo for repo in api(f"/users/{urllib.parse.quote(USER)}/repos?per_page=100&type=owner") if not repo.get("fork") and repo.get("name") != USER]
    language_bytes = {}
    for repo in repos:
        try:
            for language, amount in api(f"/repos/{USER}/{urllib.parse.quote(repo['name'])}/languages").items():
                language_bytes[language] = language_bytes.get(language, 0) + amount
        except Exception as error:
            print(f"skip languages for {repo.get('name')}: {error}")
    (OUT / "stats.svg").write_text(build_stats(user, repos), encoding="utf-8")
    (OUT / "langs.svg").write_text(build_languages(language_bytes), encoding="utf-8")
    (OUT / "repos.svg").write_text(build_repos(repos), encoding="utf-8")
    print(f"generated stats for {USER}: repos={len(repos)} languages={len(language_bytes)}")


if __name__ == "__main__":
    main()
